# Generated by Django 5.1.4 on 2024-12-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appCoder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="creado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nombre",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
