# Generated by Django 5.1.4 on 2025-01-07 22:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appCoder", "0003_profesor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profesor",
            options={"verbose_name": "Profesor", "verbose_name_plural": "Profesores"},
        ),
    ]
