# Generated by Django 5.1.4 on 2025-01-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appCoder", "0005_curso_estado_curso_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("apellido", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
